<?php

/** @noinspection AnonymousFunctionStaticInspection */
/** @noinspection StaticClosureCanBeUsedInspection */
/** @noinspection PhpVoidFunctionResultUsedInspection */
declare(strict_types=1);

namespace Guanguans\RectorRulesTests\Rector\Declare_\AddNoinspectionsDocCommentToDeclareRector\Fixture;

?>
-----
<?php

/** @noinspection AnonymousFunctionStaticInspection */
/** @noinspection NullPointerExceptionInspection */
/** @noinspection PhpPossiblePolymorphicInvocationInspection */
/** @noinspection PhpUnhandledExceptionInspection */
/** @noinspection StaticClosureCanBeUsedInspection */
/** @noinspection PhpVoidFunctionResultUsedInspection */
declare(strict_types=1);

namespace Guanguans\RectorRulesTests\Rector\Declare_\AddNoinspectionsDocCommentToDeclareRector\Fixture;

?>
